### ISSUE TITLE
Help running

### ISSUE THREAD

**Issue by benmccann** [p768lwy3/gin-server-timing#2]
I tried to use this library in a very simple example here: https://github.com/benmccann/photoprism/commit/296e2aae361cdbfc550ae8906e1a14c44aac8c07

I'm not seeing any header written. Am I doing something stupid? I'm an experienced developer, but this is my first time using Go. Thanks!

**Comment by benmccann** [comment]
Hmm, I think the issue might be that Gin won't let you write headers in middleware after `Next` is called to handle the request. Or at least it's not easy to figure out how to do that

**Comment by p768lwy3** [comment]
> Hmm, I think the issue might be that Gin won't let you write headers in middleware after `Next` is called to handle the request. Or at least it's not easy to figure out how to do that

Yes, you are correct if I remember correctly, so the method is called in the handler instead of middleware, but we can still find if there is any way to overwrite the header after ```c.Next```.

**Comment by benmccann** [comment]
I'm going to close this with the view that it's not possible. If we find a way later we can reopen
